### ISSUE TITLE
GPT API

### ISSUE THREAD

**Issue by darshansharma** [darshansharma/snorlax#2]
It would be good if anyone could integrate ChatGPT option to use and then use the API provided by the OpenAI

**Comment by aadarshmani** [comment]
Hi, I can get this working, will setup a .env file to store the API keys though.

**Comment by harshkasat** [comment]
@darshansharma  Can I work on connecting the GPT API? Even further I am able to connect the GPT API with Langchain. Please assign me also under hacktoberfest label

**Comment by harshkasat** [comment]
@darshansharma It has been two days since I submitted the PR. Can you please check it out?

**Comment by darshansharma** [comment]
Solved
